[tool.poetry]
name = "rental-service"
version = "0.1.0"
description = "Apartment rental service"

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
include = ["backend"]
extraPaths = ["backend"] 